create extension if not exists pgcrypto;
create schema if not exists private;
create type public.participant_type as enum ('guardian','shelter','petbiz','rave_vendor','platform_admin');
create type public.organization_type as enum ('shelter','rescue','pet_business','rave_vendor');
create type public.market_channel as enum ('pet','rave','shared');
create type public.record_status as enum ('draft','submitted','active','suspended','rejected','expired');
create type public.verification_status as enum ('draft','submitted','delivery_pending','sent','viewed','confirmed','declined','more_information_requested','delivery_failed','expired','canceled');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null default '', phone text, instagram_handle text, avatar_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.participant_roles (user_id uuid not null references public.profiles on delete cascade, participant_type public.participant_type not null, created_at timestamptz not null default now(), primary key(user_id,participant_type));
create table public.organizations (id uuid primary key default gen_random_uuid(), created_by uuid not null references public.profiles, organization_type public.organization_type not null, public_name text not null, legal_name text, description text, public_email text, public_phone text, website_url text, instagram_handle text, service_area text, logo_path text, status public.record_status not null default 'draft', verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_memberships (organization_id uuid not null references public.organizations on delete cascade, user_id uuid not null references public.profiles on delete cascade, role text not null default 'administrator' check(role in ('administrator','publisher','member')), status text not null default 'active' check(status in ('invited','active','revoked')), created_at timestamptz not null default now(), primary key(organization_id,user_id));
create table public.pets (id uuid primary key default gen_random_uuid(), created_by uuid not null references public.profiles, name text not null, species text not null, breed text, approximate_birth_date date, sex text, photo_path text, adopted_self_reported boolean, shelter_confirmed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.guardianships (pet_id uuid not null references public.pets on delete cascade, guardian_id uuid not null references public.profiles on delete cascade, relationship text not null default 'primary' check(relationship in ('primary','co_guardian')), started_at timestamptz not null default now(), ended_at timestamptz, primary key(pet_id,guardian_id,started_at));
create table public.adoption_verification_requests (id uuid primary key default gen_random_uuid(), pet_id uuid not null references public.pets on delete cascade, requested_by uuid not null references public.profiles, shelter_name text not null, shelter_contact_name text, shelter_email text, shelter_phone text, shelter_website_or_social text, pet_name_at_adoption text, approximate_adoption_date date, guardian_match_details text, contact_consent_at timestamptz not null, status public.verification_status not null default 'draft', token_digest text, token_expires_at timestamptz, sent_at timestamptz, viewed_at timestamptz, responded_at timestamptz, response_adoption_date date, responder_name text, responder_role text, responder_notes text, evidence_path text, reminder_count smallint not null default 0 check(reminder_count between 0 and 3), next_reminder_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(shelter_email is not null or shelter_phone is not null or shelter_website_or_social is not null));
create table public.offers (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations on delete cascade, created_by uuid not null references public.profiles, channel public.market_channel not null, title text not null, summary text not null, details text, category text not null, classification text not null default 'partner_published' check(classification in ('public_program','partner_published','exclusive','verified_adoption','sponsored','affiliate','community')), destination_url text, eligibility text, redemption_instructions text, starts_at timestamptz, expires_at timestamptz, last_verified_at timestamptz, status public.record_status not null default 'draft', published_at timestamptz, suspended_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(expires_at is null or starts_at is null or expires_at>starts_at));
create table public.organization_connections (id uuid primary key default gen_random_uuid(), requester_organization_id uuid not null references public.organizations on delete cascade, recipient_organization_id uuid not null references public.organizations on delete cascade, connection_type text not null check(connection_type in ('preferred_vendor','community_partner','shared_owner','other')), status text not null default 'pending' check(status in ('pending','accepted','declined','ended')), created_by uuid not null references public.profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(requester_organization_id<>recipient_organization_id));
create table public.offer_comments (id uuid primary key default gen_random_uuid(), offer_id uuid not null references public.offers on delete cascade, author_id uuid not null references public.profiles, body text not null check(char_length(body) between 1 and 2000), status text not null default 'visible' check(status in ('visible','hidden','removed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), created_by uuid not null references public.profiles, subject text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.conversation_participants (conversation_id uuid not null references public.conversations on delete cascade, user_id uuid not null references public.profiles on delete cascade, joined_at timestamptz not null default now(), left_at timestamptz, primary key(conversation_id,user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations on delete cascade, sender_id uuid not null references public.profiles, body text not null check(char_length(body) between 1 and 5000), created_at timestamptz not null default now());
create table private.audit_events (id bigint generated always as identity primary key, actor_id uuid references auth.users, action text not null, target_type text not null, target_id uuid, outcome text not null, context jsonb not null default '{}', created_at timestamptz not null default now());

create function private.touch() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now(); return new; end$$;
create function private.is_org_member(org uuid, roles text[] default array['administrator','publisher','member']) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.organization_memberships where organization_id=org and user_id=(select auth.uid()) and status='active' and role=any(roles))$$;
create function private.in_conversation(convo uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.conversation_participants where conversation_id=convo and user_id=(select auth.uid()) and left_at is null)$$;
revoke all on schema private from public,anon,authenticated; grant usage on schema private to authenticated;
revoke all on function private.is_org_member(uuid,text[]) from public; revoke all on function private.in_conversation(uuid) from public;
grant execute on function private.is_org_member(uuid,text[]) to authenticated; grant execute on function private.in_conversation(uuid) to authenticated;

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$declare kind public.participant_type; begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); begin kind:=(new.raw_user_meta_data->>'onboarding_type')::public.participant_type; exception when others then kind:='guardian'; end; if kind='platform_admin' then kind:='guardian'; end if; insert into public.participant_roles values(new.id,kind,now()) on conflict do nothing; return new; end$$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();
do $$declare t text; begin foreach t in array array['profiles','organizations','pets','adoption_verification_requests','offers','organization_connections','offer_comments','conversations'] loop execute format('create trigger %I_touch before update on public.%I for each row execute function private.touch()',t,t); end loop; end$$;

alter table public.profiles enable row level security; alter table public.participant_roles enable row level security; alter table public.organizations enable row level security; alter table public.organization_memberships enable row level security; alter table public.pets enable row level security; alter table public.guardianships enable row level security; alter table public.adoption_verification_requests enable row level security; alter table public.offers enable row level security; alter table public.organization_connections enable row level security; alter table public.offer_comments enable row level security; alter table public.conversations enable row level security; alter table public.conversation_participants enable row level security; alter table public.messages enable row level security;
-- Defense in depth for the non-exposed audit store. Intentionally no client policies.
alter table private.audit_events enable row level security;

create policy self_profile_read on public.profiles for select to authenticated using(id=(select auth.uid())); create policy self_profile_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy self_roles_read on public.participant_roles for select to authenticated using(user_id=(select auth.uid())); create policy self_roles_add on public.participant_roles for insert to authenticated with check(user_id=(select auth.uid()) and participant_type<>'platform_admin');
create policy org_read on public.organizations for select to anon,authenticated using(status='active' or created_by=(select auth.uid()) or private.is_org_member(id)); create policy org_add on public.organizations for insert to authenticated with check(created_by=(select auth.uid()) and verified_at is null); create policy org_edit on public.organizations for update to authenticated using(created_by=(select auth.uid()) or private.is_org_member(id,array['administrator'])) with check(created_by=(select auth.uid()) or private.is_org_member(id,array['administrator']));
create policy member_read on public.organization_memberships for select to authenticated using(user_id=(select auth.uid()) or private.is_org_member(organization_id,array['administrator'])); create policy member_add on public.organization_memberships for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.organizations where id=organization_id and created_by=(select auth.uid()))); create policy member_edit on public.organization_memberships for update to authenticated using(private.is_org_member(organization_id,array['administrator'])) with check(private.is_org_member(organization_id,array['administrator']));
create policy pet_read on public.pets for select to authenticated using(created_by=(select auth.uid()) or exists(select 1 from public.guardianships where pet_id=id and guardian_id=(select auth.uid()) and ended_at is null)); create policy pet_add on public.pets for insert to authenticated with check(created_by=(select auth.uid()) and shelter_confirmed_at is null); create policy pet_edit on public.pets for update to authenticated using(created_by=(select auth.uid())) with check(created_by=(select auth.uid()));
create policy guardian_read on public.guardianships for select to authenticated using(guardian_id=(select auth.uid())); create policy guardian_add on public.guardianships for insert to authenticated with check(guardian_id=(select auth.uid()) and exists(select 1 from public.pets where id=pet_id and created_by=(select auth.uid())));
create policy verification_read on public.adoption_verification_requests for select to authenticated using(requested_by=(select auth.uid())); create policy verification_add on public.adoption_verification_requests for insert to authenticated with check(requested_by=(select auth.uid()) and exists(select 1 from public.pets where id=pet_id and created_by=(select auth.uid()))); create policy verification_edit on public.adoption_verification_requests for update to authenticated using(requested_by=(select auth.uid()) and status in ('draft','more_information_requested')) with check(requested_by=(select auth.uid()));
create policy public_offer_read on public.offers for select to anon,authenticated using(status='active' and published_at is not null and (expires_at is null or expires_at>now())); create policy member_offer_read on public.offers for select to authenticated using(private.is_org_member(organization_id)); create policy member_offer_add on public.offers for insert to authenticated with check(created_by=(select auth.uid()) and private.is_org_member(organization_id,array['administrator','publisher'])); create policy member_offer_edit on public.offers for update to authenticated using(private.is_org_member(organization_id,array['administrator','publisher'])) with check(created_by=(select auth.uid()));
create policy connection_read on public.organization_connections for select to authenticated using(private.is_org_member(requester_organization_id) or private.is_org_member(recipient_organization_id)); create policy connection_add on public.organization_connections for insert to authenticated with check(created_by=(select auth.uid()) and private.is_org_member(requester_organization_id,array['administrator']));
create policy comment_read on public.offer_comments for select to authenticated using(status='visible' and exists(select 1 from public.offers where id=offer_id and status='active')); create policy comment_add on public.offer_comments for insert to authenticated with check(author_id=(select auth.uid()) and status='visible'); create policy comment_edit on public.offer_comments for update to authenticated using(author_id=(select auth.uid())) with check(author_id=(select auth.uid()) and status in ('visible','removed'));
create policy conversation_read on public.conversations for select to authenticated using(private.in_conversation(id)); create policy conversation_add on public.conversations for insert to authenticated with check(created_by=(select auth.uid())); create policy participant_read on public.conversation_participants for select to authenticated using(private.in_conversation(conversation_id)); create policy participant_add on public.conversation_participants for insert to authenticated with check(exists(select 1 from public.conversations where id=conversation_id and created_by=(select auth.uid()))); create policy message_read on public.messages for select to authenticated using(private.in_conversation(conversation_id)); create policy message_add on public.messages for insert to authenticated with check(sender_id=(select auth.uid()) and private.in_conversation(conversation_id));

grant usage on schema public to anon,authenticated; grant select on public.organizations,public.offers to anon; grant select,insert,update,delete on all tables in schema public to authenticated; revoke all on private.audit_events from public,anon,authenticated;
create index org_member_user on public.organization_memberships(user_id) where status='active'; create index active_guardian on public.guardianships(guardian_id) where ended_at is null; create index due_verifications on public.adoption_verification_requests(status,next_reminder_at); create index active_offers on public.offers(channel,published_at desc) where status='active'; create index offer_comments_time on public.offer_comments(offer_id,created_at); create index conversation_messages on public.messages(conversation_id,created_at);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('pet-photos','pet-photos',false,5242880,array['image/jpeg','image/png','image/webp']),('organization-assets','organization-assets',true,5242880,array['image/jpeg','image/png','image/webp','image/svg+xml']),('adoption-evidence','adoption-evidence',false,10485760,array['application/pdf','image/jpeg','image/png']) on conflict(id) do nothing;
create policy own_pet_photo_read on storage.objects for select to authenticated using(bucket_id='pet-photos' and (storage.foldername(name))[1]=(select auth.uid())::text); create policy own_pet_photo_add on storage.objects for insert to authenticated with check(bucket_id='pet-photos' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy public_org_assets on storage.objects for select to anon,authenticated using(bucket_id='organization-assets'); create policy member_org_asset_add on storage.objects for insert to authenticated with check(bucket_id='organization-assets' and private.is_org_member(((storage.foldername(name))[1])::uuid,array['administrator','publisher']));
create policy own_evidence_read on storage.objects for select to authenticated using(bucket_id='adoption-evidence' and (storage.foldername(name))[1]=(select auth.uid())::text); create policy own_evidence_add on storage.objects for insert to authenticated with check(bucket_id='adoption-evidence' and (storage.foldername(name))[1]=(select auth.uid())::text);

create index audit_actor on private.audit_events(actor_id);
create index verification_pet on public.adoption_verification_requests(pet_id);
create index verification_requester on public.adoption_verification_requests(requested_by);
create index conversation_participant_user on public.conversation_participants(user_id);
create index conversation_creator on public.conversations(created_by);
create index message_sender on public.messages(sender_id);
create index comment_author on public.offer_comments(author_id);
create index offer_creator on public.offers(created_by);
create index offer_organization on public.offers(organization_id);
create index connection_creator on public.organization_connections(created_by);
create index connection_recipient on public.organization_connections(recipient_organization_id);
create index connection_requester on public.organization_connections(requester_organization_id);
create index organization_creator on public.organizations(created_by);
create index pet_creator on public.pets(created_by);

drop policy public_offer_read on public.offers;
drop policy member_offer_read on public.offers;
create policy offer_read on public.offers for select to anon,authenticated using(
  (status='active' and published_at is not null and (expires_at is null or expires_at>now()))
  or (organization_id is not null and private.is_org_member(organization_id))
);
